version: 1.2
workflows:
   -  name: cardEndToEndVcfMethyl
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/cardEndToEndVcf.wdl
   -  name: pepperMarginDvWorkflow
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/pepper_margin_deepvariant.wdl
   -  name: hapdiffWorkflow
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/hapdiff.wdl
   -  name: dvMargin
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/dvMargin.wdl
   -  name: snifflesWorkflow
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/sniffles.wdl
   -  name: minimapWorkflow
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/minimap.wdl
   -  name: marginPhase
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/marginPhase.wdl
   -  name: shasta
      subclass: WDL
      primaryDescriptorPath: /wdl/tasks/shasta.wdl
   -  name: shastaHapdup
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/shasta_hapdup_denovo.wdl
   -  name: modkit
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/modkit.wdl
   -  name: modbamtools
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/modbamtools.wdl
   - name: glnexus
        subclass: WDL
        primaryDescriptorPath: cohort_wdl/workflows/glnexus.wdl